#!/usr/bin/env bash

WORKSPACEDIR="$(mktemp -d -p /var/tmp baseimg-tmp.XXXXXX)"
IMAGE_TAG=$1
DOCKER_REGISTRY=$2
DOCKER_USER=$3
DOCKER_PWD=$4

#Install necessary packages
apt-get update && apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common

#Add Repo, Install, Start and enable docker
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

apt-get update && apt-get install -y multistrap docker-ce docker-ce-cli containerd.io

#Configuration for multistrap
cat << EOF | tee ${WORKSPACEDIR}/jammy.conf
[General]
arch=amd64
directory=ubuntu_jammy
cleanup=true
noauth=false
explicitsuite=false
unpack=true
bootstrap=jammy jammy-updates jammy-security

[jammy]
packages=apt curl wget bash
source=http://archive.ubuntu.com/ubuntu
keyring=ubuntu-keyring
suite=jammy
components=main multiverse restricted universe

[jammy-updates]
packages=apt curl wget bash
source=http://archive.ubuntu.com/ubuntu
suite=jammy-updates
components=main multiverse restricted universe

[jammy-security]
packages=apt curl wget bash
source=http://archive.ubuntu.com/ubuntu
suite=jammy-security
components=main multiverse restricted universe
EOF

cat << EOF | tee ${WORKSPACEDIR}/noble.conf
[General]
arch=amd64
directory=ubuntu_noble
cleanup=true
noauth=false
explicitsuite=false
unpack=true
bootstrap=noble noble-updates noble-security

[noble]
packages=apt curl wget bash
source=http://archive.ubuntu.com/ubuntu
keyring=ubuntu-keyring
suite=noble
components=main multiverse restricted universe

[noble-updates]
packages=apt curl wget bash
source=http://archive.ubuntu.com/ubuntu
suite=noble-updates
components=main multiverse restricted universe

[noble-security]
packages=apt curl wget bash
source=http://archive.ubuntu.com/ubuntu
suite=noble-security
components=main multiverse restricted universe
EOF

#Build image using multistrap
cd ${WORKSPACEDIR}
multistrap -f ${WORKSPACEDIR}/${IMAGE_TAG}.conf
tar -C ubuntu_${IMAGE_TAG} -c . | docker import - "${DOCKER_REGISTRY}/${DOCKER_USER}/ubuntu:${IMAGE_TAG}"

#Login and push docker image
docker login ${DOCKER_REGISTRY} -u ${DOCKER_USER} -p ${DOCKER_PWD}
docker push ${DOCKER_REGISTRY}/${DOCKER_USER}/ubuntu:${IMAGE_TAG}
